# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20150116010930) do

  create_table "arterioscleroses", force: true do |t|
    t.integer  "member_id"
    t.string   "name"
    t.string   "team"
    t.integer  "sex"
    t.integer  "age"
    t.decimal  "height"
    t.decimal  "HR"
    t.decimal  "Rb_DIA"
    t.decimal  "Rb_SYS"
    t.decimal  "Lb_SYS"
    t.decimal  "Lb_DIA"
    t.decimal  "Ra_SYS"
    t.decimal  "Ra_DIA"
    t.decimal  "La_SYS"
    t.decimal  "La_DIA"
    t.decimal  "R_stiffness"
    t.decimal  "L_stiffness"
    t.decimal  "L_vasoocclusion"
    t.decimal  "R_vasoocclusion"
    t.datetime "operation_time"
    t.string   "remark"
    t.string   "expert_comments"
    t.string   "device_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "balance_data", force: true do |t|
    t.integer  "o_id"
    t.integer  "balance_id"
    t.decimal  "STD_velocity"
    t.decimal  "romberg_quotient"
    t.decimal  "mean_x"
    t.decimal  "mean_y"
    t.decimal  "standard_dev_x"
    t.decimal  "standard_dev_y"
    t.decimal  "feft_weight_distribution"
    t.decimal  "right_weight_distribution"
    t.decimal  "trace_length"
    t.decimal  "C90_area2"
    t.integer  "single"
    t.integer  "optimistic_lock_field"
    t.integer  "GC_cecord"
    t.text     "context"
    t.string   "performance_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "balances", force: true do |t|
    t.integer  "o_id"
    t.string   "team"
    t.decimal  "height"
    t.string   "remark"
    t.string   "valuation"
    t.string   "expert_comments"
    t.datetime "operation_time"
    t.integer  "member_id"
    t.string   "name"
    t.integer  "age"
    t.integer  "sex"
    t.string   "protocol"
    t.integer  "perf_times"
    t.integer  "optimistic_lock_field"
    t.integer  "GC_record"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "blood_pressures", force: true do |t|
    t.integer  "member_id"
    t.integer  "diastolic"
    t.integer  "systolic"
    t.integer  "pulse"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "blood_sugars", force: true do |t|
    t.integer  "test_type"
    t.float    "result"
    t.integer  "member_id"
    t.datetime "measure_time"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "body_temperatures", force: true do |t|
    t.float    "result"
    t.integer  "member_id"
    t.datetime "measure_time"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "categories", force: true do |t|
    t.string   "name"
    t.string   "description"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "category_items", force: true do |t|
    t.string   "name"
    t.integer  "category_id"
    t.string   "item_tag"
    t.integer  "definition_type"
    t.integer  "result_type"
    t.string   "description"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "cholesterins", force: true do |t|
    t.integer  "test_type"
    t.float    "result"
    t.integer  "member_id"
    t.datetime "measure_time"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "diabetes", force: true do |t|
    t.integer  "member_id"
    t.integer  "age"
    t.integer  "sex"
    t.integer  "level"
    t.integer  "risk"
    t.string   "name"
    t.string   "remark"
    t.string   "expert_comments"
    t.string   "device_type"
    t.string   "team"
    t.decimal  "IR"
    t.decimal  "DC"
    t.decimal  "IGT"
    t.decimal  "Fsi"
    t.decimal  "height"
    t.decimal  "Cn"
    t.datetime "operation_time"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "doctor_communicate_members", force: true do |t|
    t.integer  "doctor_id"
    t.integer  "member_id"
    t.text     "msg"
    t.string   "sending"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "doctors", force: true do |t|
    t.string   "name"
    t.string   "password_digest"
    t.string   "avatar"
    t.string   "tel"
    t.string   "sex"
    t.text     "introduce"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "health_aerobics", force: true do |t|
    t.integer  "member_id"
    t.string   "name"
    t.string   "team"
    t.integer  "sex"
    t.integer  "age"
    t.text     "Hrs"
    t.text     "HtHR"
    t.datetime "operation_time"
    t.string   "remark"
    t.string   "expert_comments"
    t.string   "device_type"
    t.decimal  "max_oxygen"
    t.decimal  "height"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "health_bmds", force: true do |t|
    t.integer  "member_id"
    t.string   "name"
    t.string   "remark"
    t.string   "expert_comments"
    t.string   "device_type"
    t.string   "team"
    t.integer  "sex"
    t.integer  "age"
    t.decimal  "TI"
    t.decimal  "Z"
    t.decimal  "height"
    t.decimal  "BMD"
    t.datetime "operation_time"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "members", force: true do |t|
    t.string   "name"
    t.string   "password_digest"
    t.string   "avatar"
    t.string   "tel"
    t.string   "sex"
    t.integer  "doctor_id"
    t.date     "birthday"
    t.text     "health"
    t.string   "building"
    t.string   "unit"
    t.string   "house"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "national_physicals", force: true do |t|
    t.integer  "member_id"
    t.integer  "age"
    t.integer  "sex"
    t.integer  "weight_score"
    t.integer  "BMR_score"
    t.integer  "body_flexion_score"
    t.integer  "step_index_score"
    t.integer  "FVC_score"
    t.integer  "vertical_jump_score"
    t.integer  "push_up_score"
    t.integer  "grip_score"
    t.integer  "one_leg_standing_score"
    t.integer  "reaction_score"
    t.integer  "situp_score"
    t.string   "name"
    t.string   "team"
    t.string   "remark"
    t.string   "expert_comments"
    t.string   "device_type"
    t.decimal  "weight"
    t.decimal  "BMI"
    t.decimal  "FVC"
    t.decimal  "BMR"
    t.decimal  "height"
    t.decimal  "grip"
    t.decimal  "body_flexion"
    t.decimal  "step_index"
    t.decimal  "vertical_jump"
    t.decimal  "push_up"
    t.decimal  "reaction"
    t.decimal  "situp"
    t.datetime "operation_time"
    t.decimal  "one_leg_standing"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "new_in_bodies", force: true do |t|
    t.integer  "member_id"
    t.integer  "sex"
    t.integer  "in_body_type"
    t.integer  "age"
    t.integer  "nutritional_assessment_salt"
    t.integer  "nutritional_assessment_fat"
    t.integer  "nutritional_assessment_edema"
    t.integer  "manage_skeletal_muscle"
    t.integer  "manage_fat"
    t.integer  "fat_analysis_percent_body_fat"
    t.integer  "fat_analysis_WHR"
    t.integer  "balanced_analysis_arm_leg"
    t.integer  "physical_strength_arm"
    t.integer  "physical_strength_Leg"
    t.integer  "physical_strength_muscle"
    t.integer  "health_diagnosis_body_water"
    t.integer  "health_diagnosis_life_pattern"
    t.integer  "muscle_low"
    t.integer  "up_down_leg"
    t.integer  "segment_lean_right_arm_rating"
    t.integer  "segment_lean_right_leg_rating"
    t.integer  "segment_lean_left_leg_rating"
    t.integer  "obesity_degree_rating"
    t.integer  "BMR_rating"
    t.integer  "segment_lean_trunk_rating"
    t.integer  "segment_lean_left_arm_rating"
    t.integer  "left_right_leg"
    t.integer  "left_righ_arm"
    t.integer  "up_down_arm"
    t.integer  "muscle_muscle"
    t.integer  "muscle_conventional"
    t.integer  "health_diagnosis_edema"
    t.integer  "balanced_analysis_leg"
    t.integer  "balanced_analysis_arm"
    t.integer  "fat_analysis_BMI"
    t.integer  "manage_weight"
    t.integer  "nutritional_assessment_protein"
    t.integer  "fitness_score"
    t.string   "teams"
    t.string   "name"
    t.decimal  "height"
    t.decimal  "weight"
    t.decimal  "intercellular_water"
    t.string   "idea_intercellular_water"
    t.decimal  "extracellular_water"
    t.decimal  "protein_mass"
    t.decimal  "body_fat_mass"
    t.decimal  "minerl_mass"
    t.decimal  "total_body_water"
    t.decimal  "bone_mineral_contents"
    t.decimal  "soft_lean_mass"
    t.decimal  "fat_free_mass"
    t.decimal  "target_weight"
    t.decimal  "weight_control"
    t.decimal  "fat_control"
    t.decimal  "muscle_control"
    t.decimal  "visceral_fat_area"
    t.decimal  "ECF_TBF_right_arm_edema"
    t.decimal  "ECF_TBF_left_leg_edema"
    t.decimal  "ECF_TBF_right_leg_edema"
    t.decimal  "ECW_TBW_right_arm_edema"
    t.decimal  "ECW_TBW_left_arm_edema"
    t.decimal  "ECW_TBW_right_leg_edema"
    t.decimal  "ECW_TBW_left_leg_edema"
    t.decimal  "ECW_TBW_edema"
    t.decimal  "percent_weight"
    t.decimal  "ECF_TBF_edema"
    t.decimal  "ECW_TBW_trunk_edema"
    t.decimal  "ECF_TBF_trunk_edema"
    t.decimal  "ECF_TBF_left_arm_edema"
    t.decimal  "skeletal_muscle_mass"
    t.decimal  "percent_skeletal_muscle_mass"
    t.decimal  "percent_body_fat_mass"
    t.decimal  "BMI"
    t.decimal  "percent_BMI"
    t.decimal  "percent_body_fat"
    t.decimal  "WHR"
    t.decimal  "right_arm"
    t.decimal  "left_arm"
    t.decimal  "trunk"
    t.decimal  "left_leg"
    t.decimal  "percent_left_leg"
    t.decimal  "percent_right_leg"
    t.decimal  "right_leg"
    t.decimal  "percent_trunk"
    t.decimal  "percent_left_arm"
    t.decimal  "percent_right_arm"
    t.decimal  "percent_soft_lean_mass"
    t.decimal  "percent_height"
    t.decimal  "segment_lean_right_arm"
    t.decimal  "segment_lean_left_arm"
    t.decimal  "segment_lean_trunk"
    t.decimal  "segment_lean_right_leg"
    t.decimal  "segment_lean_left_leg"
    t.decimal  "percent_segment_lean_right_arm"
    t.decimal  "percent_segment_lean_left_arm"
    t.decimal  "percent_segment_lean_trunk"
    t.decimal  "percent_segment_lean_right_leg"
    t.decimal  "percent_segment_lean_left_leg"
    t.decimal  "ideal_percent_lean_right_arm"
    t.decimal  "ideal_percent_lean_left_arm"
    t.decimal  "ideal_percent_lean_trunk"
    t.decimal  "ideal_percent_lean_right_leg"
    t.decimal  "ideal_percent_lean_left_leg"
    t.decimal  "obesity_degree"
    t.decimal  "BMR"
    t.string   "idea_WHR"
    t.string   "expert_comments"
    t.string   "idea_body_fat"
    t.string   "idea_BMI"
    t.string   "idea_skeleta_muscle_mass"
    t.string   "idea_fat_free_mass"
    t.string   "idea_body_water"
    t.string   "idea_minerl_mass"
    t.string   "idea_weight"
    t.string   "idea_protein_mass"
    t.string   "idea_body_fat_mass"
    t.string   "idea_extracellular_water"
    t.datetime "operation_time"
    t.text     "data"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "phy_exam_record_extras", force: true do |t|
    t.integer  "phy_exam_record_id"
    t.integer  "category_id"
    t.string   "doctor"
    t.text     "content"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "phy_exam_record_items", force: true do |t|
    t.integer  "phy_exam_record_id"
    t.integer  "phy_exam_tpl_item_id"
    t.string   "result"
    t.integer  "category_id"
    t.string   "decide"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "phy_exam_records", force: true do |t|
    t.integer  "phy_exam_tpl_id"
    t.integer  "member_id"
    t.date     "phy_exam_date"
    t.integer  "doctor_id"
    t.string   "phy_records_file"
    t.text     "phy_tpl_conclusion"
    t.text     "phy_tpl_advise"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "phy_exam_stand_results", force: true do |t|
    t.string   "name"
    t.integer  "phy_exam_tpl_item_id"
    t.integer  "definition_type"
    t.string   "unit"
    t.string   "device"
    t.integer  "result_type_id"
    t.integer  "normal_max"
    t.integer  "normal_min"
    t.string   "description"
    t.text     "result_text"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "phy_exam_tpl_items", force: true do |t|
    t.integer  "phy_exam_tpl_id"
    t.integer  "category_item_id"
    t.string   "alias_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "phy_exam_tpls", force: true do |t|
    t.string   "name"
    t.string   "description"
    t.string   "agency"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "purine_triones", force: true do |t|
    t.integer  "test_type"
    t.float    "result"
    t.integer  "member_id"
    t.datetime "measure_time"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "result_types", force: true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "zhong_yi_ti_zhis", force: true do |t|
    t.integer  "member_id"
    t.string   "result"
    t.integer  "unique_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
