class CreateNewInBodies < ActiveRecord::Migration
  def change
    create_table :new_in_bodies do |t|
    	t.integer  :member_id
	    t.integer  :sex
	    t.integer  :in_body_type
	    t.integer  :age
	    t.integer  :nutritional_assessment_salt
	    t.integer  :nutritional_assessment_fat
	    t.integer  :nutritional_assessment_edema
	    t.integer  :manage_skeletal_muscle
	    t.integer  :manage_fat
	    t.integer  :fat_analysis_percent_body_fat
	    t.integer  :fat_analysis_WHR
	    t.integer  :balanced_analysis_arm_leg
	    t.integer  :physical_strength_arm
	    t.integer  :physical_strength_Leg
	    t.integer  :physical_strength_muscle
	    t.integer  :health_diagnosis_body_water
	    t.integer  :health_diagnosis_life_pattern
	    t.integer  :muscle_low
	    t.integer  :up_down_leg
	    t.integer  :segment_lean_right_arm_rating
	    t.integer  :segment_lean_right_leg_rating
	    t.integer  :segment_lean_left_leg_rating
	    t.integer  :obesity_degree_rating
	    t.integer  :BMR_rating
	    t.integer  :segment_lean_trunk_rating
	    t.integer  :segment_lean_left_arm_rating
	    t.integer  :left_right_leg
	    t.integer  :left_righ_arm
	    t.integer  :up_down_arm
	    t.integer  :muscle_muscle
	    t.integer  :muscle_conventional
	    t.integer  :health_diagnosis_edema
	    t.integer  :balanced_analysis_leg
	    t.integer  :balanced_analysis_arm
	    t.integer  :fat_analysis_BMI
	    t.integer  :manage_weight
	    t.integer  :nutritional_assessment_protein
	    t.integer  :fitness_score
	    t.string   :teams
	    t.string   :name
	    t.decimal  :height
	    t.decimal  :weight
	    t.decimal  :intercellular_water
	    t.string   :idea_intercellular_water
	    t.decimal  :extracellular_water
	    t.decimal  :protein_mass
	    t.decimal  :body_fat_mass
	    t.decimal  :minerl_mass
	    t.decimal  :total_body_water
	    t.decimal  :bone_mineral_contents
	    t.decimal  :soft_lean_mass
	    t.decimal  :fat_free_mass
	    t.decimal  :target_weight
	    t.decimal  :weight_control
	    t.decimal  :fat_control
	    t.decimal  :muscle_control
	    t.decimal  :visceral_fat_area
	    t.decimal  :ECF_TBF_right_arm_edema
	    t.decimal  :ECF_TBF_left_leg_edema
	    t.decimal  :ECF_TBF_right_leg_edema
	    t.decimal  :ECW_TBW_right_arm_edema
	    t.decimal  :ECW_TBW_left_arm_edema
	    t.decimal  :ECW_TBW_right_leg_edema
	    t.decimal  :ECW_TBW_left_leg_edema
	    t.decimal  :ECW_TBW_edema
	    t.decimal  :percent_weight
	    t.decimal  :ECF_TBF_edema
	    t.decimal  :ECW_TBW_trunk_edema
	    t.decimal  :ECF_TBF_trunk_edema
	    t.decimal  :ECF_TBF_left_arm_edema
	    t.decimal  :skeletal_muscle_mass
	    t.decimal  :percent_skeletal_muscle_mass
	    t.decimal  :percent_body_fat_mass
	    t.decimal  :BMI
	    t.decimal  :percent_BMI
	    t.decimal  :percent_body_fat
	    t.decimal  :WHR
	    t.decimal  :right_arm
	    t.decimal  :left_arm
	    t.decimal  :trunk
	    t.decimal  :left_leg
	    t.decimal  :percent_left_leg
	    t.decimal  :percent_right_leg
	    t.decimal  :right_leg
	    t.decimal  :percent_trunk
	    t.decimal  :percent_left_arm
	    t.decimal  :percent_right_arm
	    t.decimal  :percent_soft_lean_mass
	    t.decimal  :percent_height
	    t.decimal  :segment_lean_right_arm
	    t.decimal  :segment_lean_left_arm
	    t.decimal  :segment_lean_trunk
	    t.decimal  :segment_lean_right_leg
	    t.decimal  :segment_lean_left_leg
	    t.decimal  :percent_segment_lean_right_arm
	    t.decimal  :percent_segment_lean_left_arm
	    t.decimal  :percent_segment_lean_trunk
	    t.decimal  :percent_segment_lean_right_leg
	    t.decimal  :percent_segment_lean_left_leg
	    t.decimal  :ideal_percent_lean_right_arm
	    t.decimal  :ideal_percent_lean_left_arm
	    t.decimal  :ideal_percent_lean_trunk
	    t.decimal  :ideal_percent_lean_right_leg
	    t.decimal  :ideal_percent_lean_left_leg
	    t.decimal  :obesity_degree
	    t.decimal  :BMR
	    t.string   :idea_WHR
	    t.string   :expert_comments
	    t.string   :idea_body_fat
	    t.string   :idea_BMI
	    t.string   :idea_skeleta_muscle_mass
	    t.string   :idea_fat_free_mass
	    t.string   :idea_body_water
	    t.string   :idea_minerl_mass
	    t.string   :idea_weight
	    t.string   :idea_protein_mass
	    t.string   :idea_body_fat_mass
	    t.string   :idea_extracellular_water
	    t.datetime :operation_time
	    t.text     :data
      t.timestamps
    end
  end
end
